# Generated by Django 3.2.5 on 2021-08-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='A small summary of your post', max_length=300),
        ),
    ]
