# Generated by Django 3.2.5 on 2021-07-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_information'),
        ('timetable', '0002_auto_20210724_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='product',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='time',
        ),
        migrations.CreateModel(
            name='TimeTableItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.timetable')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
