# Generated by Django 3.2.5 on 2021-07-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20210724_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name_plural': 'Time Table'},
        ),
        migrations.AlterModelOptions(
            name='timetableitems',
            options={'verbose_name_plural': 'Time Table Items'},
        ),
    ]
