# Generated by Django 3.2.5 on 2021-07-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_information'),
        ('timetable', '0004_auto_20210724_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
