# Generated by Django 3.2.5 on 2021-07-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_timetableitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='day_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='Monday', max_length=10),
        ),
    ]
