# Generated by Django 3.2.5 on 2021-08-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_alter_day_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='time',
            new_name='evening_time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='morning_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
