# Generated by Django 3.2.5 on 2021-07-16 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210713_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_sessions',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
