# Generated by Django 3.2.5 on 2021-07-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='location',
            new_name='information',
        ),
    ]
