# Generated by Django 3.2.5 on 2021-07-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_location_product_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
