# Generated by Django 3.2.5 on 2021-07-23 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Advanced', 'Advanced')], default='Beginner', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Difficulty',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.difficultylevel'),
        ),
    ]
