# Generated by Django 3.2.5 on 2021-07-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210723_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='information',
        ),
    ]
