# Generated by Django 3.2.5 on 2021-08-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210731_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='Mon', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='evening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='morning_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
