# Generated by Django 3.2.5 on 2021-08-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210814_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='Mon', max_length=10),
        ),
    ]
