# Generated by Django 3.2.5 on 2021-08-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['day']},
        ),
    ]
