# Generated by Django 3.2.5 on 2021-08-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='class_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
